### ISSUE TITLE
Got rid of get_model_specs?

### ISSUE THREAD

**Issue by dallenmidd** [rudeboybert/forestecology#30]
Hey Bert, I am back to working on taking the code from `pkg_todo.R` and putting it into the `README.Rmd`. I am looking at `pkg_todo.R` in the `SCBI` branch. I skipped over the blockCV stuff and got to lines 119-124 where you set the model formula. I thought that before we did this with the command `get_model_specs` so the user didn't have to get as down and dirty with all that. Just checking if you wanted to get rid of that function or maybe I am misunderstanding what you are doing in those line.

**Comment by rudeboybert** [comment]
Do you mean the 
```r
model_formula_bw <- focal_vs_comp_bw$focal_sp %>%
  unique() %>%
  sort() %>%
  paste(., "*sp", sep = "", collapse = " + ") %>%
  paste("growth ~ sp + dbh + dbh*sp + ", .)  %>%
  as.formula()
```
😱 code that creates the model formula?

If so, yeah, the reason I got rid of the `get_model_specs()` function (and moved the above 😱 code to the main script) was since we are no longer allowing for different notions of focal and competitor species, then why have a separate function. 

But maybe it is still worth having a function that defines the model formula, given how 😱 this code is? We could even call it something more specific to our paper, i.e. `get_allen_kim_model_formula()`? Thoughts?

**Comment by dallenmidd** [comment]
yeah that is the code I meant. That makes total sense, I forgot that part of `get_model_specs()` had to do with specifying different notions of species. hmm. Yeah let's think about whether we need a function to do this or just give this code. I like the name you suggest, haha!
