### ISSUE TITLE
Dave TODO's

### ISSUE THREAD

**Issue by rudeboybert** [rudeboybert/forestecology#70]
- [x] Investigate open access journal publishing funds
- [x] Brief literature review on species competition models that assume less coarse null hypothesis than we are

**Comment by dallenmidd** [comment]
In terms of the open access funds for MIddlebury they new cap it at $1600 (I think that is the result of the COVID budget crunch, not sure though). I can't apply for these funds until we get an invoice from the journal, which will happen when the paper is accepted.

**Comment by dallenmidd** [comment]
I should say the fee for this journal is just above that cap, I think it is like $1780. Not sure how difficult it would be to pay from two different accounts. I am totally fine eating the $180 if needed.

**Comment by dallenmidd** [comment]
Okay, so here are the things that I think that we could do:

- If there is a way for us to easily implement the heterospecific versus conspecific test I think that would be great. It would help address the criticism that we miss some important theory of competition. I could see `run_shuffle = all` versus `run_shuffle = conspecific` or something like that.
- The reviewer brings up two recent papers that use neighborhood models to test ideas about competition that line up with current theory. [Lasky et al 2014](https://www.pnas.org/content/111/15/5616) and [Kunstler et al 2016](Plant functional traits have globally consistent effects on competition). Both of them are use plant traits rather than plant species identity. A plant trait is something like %N in the leaves. The density of the wood. Aspects of leaf morphology. They take a numeric value. The idea is that some traits could give us an idea of how good a competitor is. All the model needs to know is a species trait value rather than species identity. For tropical forests are there too many species, and traits allow better generalizations. No matter the forest trees with higher wood density are better competitor.  Looking at Lasky and Kunstler, I think it would be easier for use to implement Kunstler. I will open a new issue where I describe how we might do that. Then we can think about whether it is worth it or not.

**Comment by rudeboybert** [comment]
- I can cover any outstanding balance for publishing
- Thanks
