### ISSUE TITLE
Problem with little or absent competition

### ISSUE THREAD

**Issue by PietroCiccale** [rudeboybert/forestecology#92]
The problem I'm facing is due to the fact that it seems that no - or very little - competition is happening within my sample plot. The bayesian model fits the data, but it does not show a "prevailing" species or individual even though DBH values are quite different: the largest individual has an 80 mm DBH, while the smallest one has a 24 mm DBH.

Also, a point that needs to be clarified: it seems that the model describe a kind of competition "within the individual itself". For instance, first column, first row, or second column, second row, and so on. The individual has a competition effect on itself?

![image](https://github.com/rudeboybert/forestecology/assets/134532331/643a4eee-5764-4f11-8223-705abbbfe6cc)

![image (1)](https://github.com/rudeboybert/forestecology/assets/134532331/3f4e1fc6-39c1-402a-9344-731006556328)

**Comment by dallenmidd** [comment]
Hi Pietro,
Thanks for using the package! I think the issue here is not with the package, but that maybe there just isn't much signal of competition in your data, so that is why all the competition coefficients are nearly zero. It does look like the model fit and found differences between the species, for example differences in how stem DBH affects stem growth which is very high for *Mabea angularis* and lower for the other species. Sorry that I don't have a suggestion for how to get more of a signal of competition.

The package does not consider an individual stem's competitive effect on itself, but it does consider the effect of other stems of the same species (conspecifics). So along the diagonal in the matrix is the competitive effect on focal stems of other individuals of the same species. 

Hope this is helpful! Let me know if you have any other questions.

**Comment by PietroCiccale** [comment]
Hi David,
It's good to hear from you.
I'm looking at the function you guys built, "create_focal_vs_comp", which
takes "comp_dist" and "comp_x_var" as the variables for the signal of
competition.
In the figures attached you can see different situations in which I've been
trying to modify such variables only to see what would happen:
Fig. 1 has basal area = 0.1 * pi * (dbh1 / 2)^2) and comp_dist = 5 ;
Fig. 2 has basal area = 0.001 * pi * (dbh1 / 2)^2) and comp_dist = 5 ;
Fig. 3 has basal area = 0.1 * pi * (dbh1 / 2)^2) and comp_dist = 2.5 ;
Fig. 4 has growth = 100 * growth and comp_dist = 2.5 (so here growth is
taken as comp_x_var).

along the diagonal in the matrix is the competitive effect on focal stems
of other individuals of the same species
Unfortunately, in the sample plot I provided there is only 1 individual for
each species, thus there shouldn't be the competitive effect derived by
individuals of the same species as you described. The same thing happens in
all the other blocks in my plot - only a few of them have individuals of
the same species -.

Thank you and looking forward to further discussions.

Best,
Pietro

Fig.1
[image: image.png]

Fig.2
[image: image.png]

Fig. 3
[image: image.png]

Fig. 4
[image: image.png]

Em ter., 7 de mai. de 2024 às 22:17, David Allen ***@***.***>
escreveu:

**Comment by dallenmidd** [comment]
Hi Pietro,
Sorry I am not sure what your question is. And it looks like the pictures didn't come through.

**Comment by PietroCiccale** [comment]
Hi David,

I don't know why the pictures has not been sent - to me, it says they have
been sent -.

Anyway, my question is more related to the validity of the functions used
to describe competition. As you said, there is conspecific competition, but
it should not be there since there is only one individual for each species.
In addition, in my case the value of basal area does not produce a good
"signal of competition" - i.e. an individual with 80 mm dbh is obviously
more competitive than and individual with 20 mm dbh, but the plot is
telling us that all individuals have a signal close to 0 - but growth
produces a more "realistic" model of competitive interactions between
plants.

As I'm writing a paper, I would like to know what you guys think about
this? Can growth be a valid replacement in my case?

I've sent to Robert a sample plot together with the R Script I'm using. If
you are interested I can send it to you too.

I appreciate your help.

Best,
Pietro


Em qui., 9 de mai. de 2024 08:57, David Allen ***@***.***>
escreveu:

**Comment by dallenmidd** [comment]
Oh okay, sorry I misunderstood! The package uses a Bayesian framework, so all of the estimated parameters start with prior distributions. For the intercept, slope, and competition coefficients all these prior distributions have mean 0. Since you have no conspecific species pairs, there is no data on conspecific competition so there will be no change to these priors. So the model outputs pretty much just the prior distribution guess of the conspecific competition coefficients.
